# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Item Name')),
                ('weight', models.CharField(blank=True, max_length=30, null=True, verbose_name='Weight')),
                ('value', models.CharField(blank=True, max_length=30, null=True, verbose_name='Value')),
                ('quantity', models.CharField(blank=True, max_length=30, null=True, verbose_name='Quantity')),
                ('unit_price', models.CharField(blank=True, max_length=30, null=True, verbose_name='Unit Price')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_from', models.CharField(blank=True, max_length=20, null=True, verbose_name='transaction From')),
                ('transaction_to', models.CharField(blank=True, max_length=20, null=True, verbose_name='Transaction To')),
                ('carreir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_name', to=settings.AUTH_USER_MODEL, verbose_name='Carrier')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.Document', verbose_name='Documents')),
                ('reciver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciver_name', to=settings.AUTH_USER_MODEL, verbose_name='Reciver')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_name', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
        ),
    ]
