# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_auto_20180723_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_doc',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='shipping_cost',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='shipping_cost'),
        ),
    ]
