# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_auto_20180723_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Item Name')),
                ('weight', models.CharField(blank=True, max_length=20, null=True, verbose_name='Weight')),
                ('value', models.CharField(blank=True, max_length=20, null=True, verbose_name='Value')),
                ('quantity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Quantity')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='document',
            name='value',
        ),
        migrations.RemoveField(
            model_name='document',
            name='weight',
        ),
        migrations.AddField(
            model_name='document',
            name='item_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shipping.Item'),
            preserve_default=False,
        ),
    ]
