# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_auto_20180725_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='item_details',
        ),
        migrations.AddField(
            model_name='item',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shipping.Document'),
            preserve_default=False,
        ),
    ]
