# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0008_auto_20180725_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Unit Price'),
        ),
    ]
