# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0013_auto_20180725_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='carreir_otp',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Carrier OTP'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='carrier_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='carrier_delivery_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reciver_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reciver_otp',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Reciver OTP'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='taken_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
