# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0014_auto_20180726_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
