# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0015_auto_20180728_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from', to='cities_light.City', verbose_name='Transaction From'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_to', to='cities_light.City', verbose_name='Transaction To'),
        ),
    ]
