# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0017_auto_20180730_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='carreir_address',
            field=models.TextField(blank=True, null=True, verbose_name='Carreir Aaddress'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_address',
            field=models.TextField(blank=True, null=True, verbose_name='receiver_address'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_address',
            field=models.TextField(blank=True, null=True, verbose_name='Sender Address'),
        ),
    ]
