# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0018_auto_20180730_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('UK', 'POUNT,'), ('US', '$'), ('EUROPE', 'EURO'), ('INDIA', 'Rupee)')], default=1, max_length=20, verbose_name='currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='weight',
            field=models.CharField(choices=[('lB', 'LB'), ('kg', 'KG'), ('ton', 'TON'), ('pound', 'POUND')], default=1, max_length=20, verbose_name='weight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='carreir_address',
            field=models.TextField(blank=True, null=True, verbose_name='Carreir Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_address',
            field=models.TextField(blank=True, null=True, verbose_name='Receiver address'),
        ),
    ]
