# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0021_auto_20180730_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='carreir_email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='carrier_email'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='carreir_mobileNo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='carreir_mobileNo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='receiver_email'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_mobileNo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='receiver_mobileNo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='sender_email'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_mobileNo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='sender_mobileNo'),
        ),
    ]
