# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0022_auto_20180731_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='image_doc',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('UK', 'POUNT'), ('US', '$'), ('EUROPE', 'EURO'), ('INDIA', 'RUPEE')], max_length=20, verbose_name='currency'),
        ),
    ]
